version: '3.7'

services:

  elasticsearch:
    image: 672029928308.dkr.ecr.us-east-1.amazonaws.com/ecr-alphascale-tools:elasticsearch
    container_name: elasticsearch
    volumes:
      - /home/ubuntu/efs/tools/elk:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node

  kibana:
    image: 672029928308.dkr.ecr.us-east-1.amazonaws.com/ecr-alphascale-tools:kibana
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      ELASTIC_HOST: ${ELASTIC_HOST}
    depends_on:
      - elasticsearch
