ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/kibana/kibana:8.2.0

RUN ls -al

RUN pwd

WORKDIR kibana

RUN ls

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
